name: build-docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone gocd-docker-build
      uses: actions/checkout@v2
    - name: Clone gocd/gocd from upstream
      uses: actions/checkout@v2
      with:
        repository: gocd/gocd
        ref: 21.2.0
        path: gocd-upstream
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew docker:gocd-server:ubuntu-20.04
      working-directory: gocd-upstream
