name: build-docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET_GOCD_VERSION: 21.2.0
    steps:
    - name: Clone gocd-docker-build
      uses: actions/checkout@v2
    - name: Clone gocd/gocd from upstream
      uses: actions/checkout@v2
      with:
        repository: chadlwilson/gocd
        ref: release-${{ env.TARGET_GOCD_VERSION }}
        path: gocd-upstream
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-${{ env.TARGET_GOCD_VERSION }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - id: gradle-docker-server
      name: Build with Gradle
      run: ../build-docker.sh
      working-directory: gocd-upstream
    - run: ./gradlew --stop
      working-directory: gocd-upstream
      if: ${{ always() }}
      continue-on-error: true
      
